routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController')->name('welcome');

Route::post('/contact-us', 'ContactUsController@store')->name('contact-us');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('/examples')->group(function () {
    Route::prefix('/merch')->name('examples.merch.')->group(function () {
        Route::get('/', 'MerchController@index')->name('index');
        Route::get('/create', 'MerchController@create')->name('create');
        Route::post('/', 'MerchController@store')->name('store');
        Route::get('/{merch}', 'MerchController@show')->name('show');
        Route::get('/{merch}/edit', 'MerchController@edit')->name('edit');
        Route::put('/{merch}', 'MerchController@update')->name('update');
        Route::delete('/{merch}', 'MerchController@destroy')->name('destroy');
    });
});

app/Merch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Merch extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'cost',
        'stock',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string',
        'cost' => 'integer',
        'stock' => 'integer',
    ];

    public function exactlyStock($stock)
    {
        $this->stock = $stock;
    }

    public function addStock($stock)
    {
        $this->stock += $stock;
    }

    public function subtractStock($stock)
    {
        $this->stock -= $stock;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactUsController.php
<?php

namespace App\Http\Controllers;

use App\Mail\ContactForm;
use Illuminate\Support\Facades\Mail;
use App\Http\Requests\ContactUsRequest;

class ContactUsController extends Controller
{
    public function store(ContactUsRequest $request)
    {
        $enquiry = $request->validated();

        // send message
        Mail::to('info@nickoJRuddock.com')->send(new ContactForm($enquiry));

        // redirect with message
        return redirect('/#contact')->with([
            'message' => 'Email sent successfully',
            'status' => 'success',
        ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MerchController.php
<?php

namespace App\Http\Controllers;

use App\Merch;
use App\Http\Requests\MerchRequest;
use Illuminate\Support\Arr;

class MerchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $merch_items = Merch::orderBy('created_at', 'desc')->paginate(15);
        return view('examples.merch.index', compact('merch_items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('examples.merch.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MerchRequest $request)
    {
        $newMerch = $request->validated();

        Merch::create($newMerch);

        return redirect()
            ->route('examples.merch.index')
            ->with([
                'message' => "{$newMerch['name']} created successfully",
                'status' => 'success',
            ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Merch  $merch
     * @return \Illuminate\Http\Response
     */
    public function show(Merch $merch)
    {
        return view('examples.merch.show', compact('merch'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Merch  $merch
     * @return \Illuminate\Http\Response
     */
    public function edit(Merch $merch)
    {
        return view('examples.merch.edit', compact('merch'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Merch  $merch
     * @return \Illuminate\Http\Response
     */
    public function update(MerchRequest $request, Merch $merch)
    {
        $newMerch = $request->validated();

        $stock = Arr::pull($newMerch, 'stock');
        $stockType = Arr::pull($newMerch, 'stock-type');

        $stockFunction = $stockType . 'Stock';

        $merch->{$stockFunction}($stock);
        $merch->update($newMerch);

        return back()->with([
            'message' => "Merch \"{$merch->name}\" updated successfully",
            'status' => 'success',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Merch  $merch
     * @return \Illuminate\Http\Response
     */
    public function destroy(Merch $merch)
    {
        $merchName = $merch->name;

        $merch->delete();

        return redirect()
            ->route('examples.merch.index')
            ->with([
                'message' => "\"{$merchName}\" successfully deleted",
                'status' => 'danger',
            ]);
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

class WelcomeController extends Controller
{
    public function __invoke()
    {
        return view('welcome');
    }
}

resources/views/examples/merch/components/merch_form.blade.php
<form action="{{ $action ?? null }}" method="POST">
    @csrf
    @if (in_array($method, ['PUT', 'PATCH', 'DELETE']))
        @method($method)
    @endif

    <div class="form-group form-row">
        <label for="name" class="col-sm-2 col-form-label">
            Name
        </label>
        <div class="col-sm-10">
            <input type="text"
                maxlength="255"
                class="form-control"
                name="name"
                value="{{ old('name') ?? $merch->name ?? null }}"
                placeholder="Merch item name..."
                @if('GET' === $method) readonly @endif>
        </div>
    </div>

    <div class="form-group form-row">
        <label for="cost" class="col-sm-2 col-form-label">
            Cost
        </label>
        <div class="col-sm-10 input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">£</div>
            </div>
            <input type="number"
                min="0" max="65535"
                class="form-control"
                name="cost"
                value="{{ old('cost') ?? $merch->cost ?? null }}"
                placeholder="Cost of item"
                @if('GET' === $method) readonly @endif>
        </div>
    </div>

    <div class="form-group form-row">
        <label for="stock" class="col-sm-2 col-form-label">
            Stock
        </label>
        @if (isset($action) && isset($merch->id))
            <label for="stock-type" class="sr-only">
                Amend stock type
            </label>
            <div class="col-sm-2">
                <select class="custom-select" name="stock-type">
                    <option selected value="exactly">Exactly</option>
                    <option value="add">Add</option>
                    <option value="subtract">Subtract</option>
                </select>
            </div>
        @endif
        <div class="col">
            <input type="number"
                min="0" max="65535"
                class="form-control"
                name="stock"
                value="{{ old('stock') ?? $merch->stock ?? null }}"
                placeholder="Stock level"
                @if('GET' === $method) readonly @endif>
        </div>
    </div>

    @if (isset($action))
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                Save Item
            </button>
        </div>
    @else
        <div class="form-group">
            <a href="{{ route('examples.merch.edit', ['merch' => $merch]) }}">
                <button type="button" class="btn btn-warning">
                    Edit Item
                </button>
            </a>
        </div>
    @endif
</form>

@if (isset($action) && isset($merch->id))
    <form action="{{ route('examples.merch.destroy', ['merch' => $merch]) }}" method="post">
        @csrf
        @method('DELETE')
        <div class="form-group">
            <button type="submit" class="btn btn-danger">
                Delete Item
            </button>
        </div>
    </form>
@endif

resources/views/examples/merch/create.blade.php
@extends('examples.merch.layouts.merch')

@section('title')
    Create Merch
@endsection

@section('merch_content')
    <div class="container">
        @component('examples.merch.components.merch_form', [
            'action' => route('examples.merch.store'),
            'method' => 'POST'
        ])
        @endcomponent
    </div>
@endsection

resources/views/examples/merch/edit.blade.php
@extends('examples.merch.layouts.merch')

@section('title')
    Edit Merch
@endsection

@section('merch_content')
    <div class="container">
        @component('examples.merch.components.merch_form', [
            'action' => route('examples.merch.update', ['merch' => $merch]),
            'method' => 'PUT',
            'merch' => $merch,
        ])
        @endcomponent
    </div>
@endsection

resources/views/examples/merch/index.blade.php
@extends('examples.merch.layouts.merch')

@section('title')
    Our Merch
@endsection

@section('merch_content')
    <div class="container">
        <div class="row">
            <a href="{{ route('examples.merch.create') }}">
                <button type="button" class="btn btn-success">
                    Add New Item
                </button>
            </a>
        </div>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>Name</th>
                        <th>Cost</th>
                        <th>Stock</th>
                        <th></th>
                    </tr>
                    @foreach ($merch_items as $merch)
                        <tr>
                            <td>{{ $merch->name }}</td>
                            <td>£{{ $merch->cost }}</td>
                            <td>{{ $merch->stock }}</td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Action
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item"
                                            href="{{ route('examples.merch.show', ['merch' => $merch]) }}">
                                            Show
                                        </a>
                                        <a class="dropdown-item"
                                            href="{{ route('examples.merch.edit', ['merch' => $merch]) }}">
                                            Edit
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>

            {{ $merch_items->links() }}
        </div>
    </div>
@endsection

resources/views/examples/merch/layouts/merch.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="jumbotron row">
            <div class="col-sm-12 text-center">
                <h1 class="display-3">
                    @yield('title')
                </h1>
                <a href="{{ route('examples.merch.index') }}">
                    <button class="btn btn-secondary">go to Merch index</button>
                </a>
            </div>
        </div>
    </div>

    @component('components.alert', [
        'check' => session('message'),
        'type' => session('status') ?? 'success',
    ])
        {{ session('message') }}
    @endcomponent
    
    @component('components.alert', [
        'check' => $errors->any(),
        'type' => 'danger',
    ])
        <ul>
            @foreach ($errors->all() as $message)
                <li>{{ $message }}</li>
            @endforeach
        </ul>
    @endcomponent

    @yield('merch_content')
@endsection

resources/views/examples/merch/show.blade.php
@extends('examples.merch.layouts.merch')

@section('title')
    Show Merch
@endsection

@section('merch_content')
    <div class="container">
        @component('examples.merch.components.merch_form', [
            'method' => 'GET',
            'merch' => $merch,
        ])
        @endcomponent
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111198791-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-111198791-1');
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Nicko J. Ruddock">
    <title>@yield('title') - {{ config('app.name') }}</title>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">


    <!-- Styles & assets -->
    <link rel="icon" href="{{ asset('images/favicon.ico') }}"> 
    <link rel="stylesheet" href="{{ mix('/css/app.css') }}">

    <!-- Javascript files -->
    <script defer
    type="text/javascript" 
    src="{{ mix('/js/app.js') }}">
    </script>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="0">
    
    <!-- Invisible top for scrollspy functionality -->
    <div id="top"></div>
    
    <nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark">
        <div class="container">
            <a href="/#top" class="navbar-brand">
                <h1>
                    NJR
                </h1>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-collapse-items" aria-controls="nav-collapse-items" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="nav-collapse-items" data-toggle="collapse" data-target="#nav-collapse-items">
                <div class="navbar-nav ml-auto">
                    <a href="/#top" class="nav-item nav-link">
                        Home
                    </a>
                    <a href="/#portfolio" class="nav-item nav-link">
                        Portfolio
                    </a>
                    <a href="/#contact" class="nav-item nav-link">
                        Contact
                    </a>
                </div>
            </div>
        </div> <!-- /.container -->
    </nav>

    @yield('content')

    <footer>
        <div class="container">
            <span>
                Copyright &copy; {{ now()->year }} Nicko J. Ruddock
            </span>
        </div>
    </footer>

</body>
</html>